# Configuration for Clarity Reminder
version: 1.0

reminders:
  - name: Update README & RELEASE_NOTES
    on_update:
      - src/**/*
      - lib/*
    remind_me_of:
      - README.md
      - RELEASE_NOTES.md
    message: "Don't forget to update the README & RELEASE NOTES file with the latest changes."

  - name: Documentation Update
    on_update:
      - src/api/*
    remind_me_of:
      - docs/*
    message: "Documentation needs to be updated with the latest changes."
